apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 10.99.162.209:8083/repository/docker-repo/node-app:latest
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database-name
        
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: nexus-cred

