apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: 10.106.148.66:8083/repository/docker-repo/node-app:latest
        env:
        - name: HOST
          value: mysql
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user-password
        - name: USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database-name
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: nexus-cred
