pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = "http://10.105.150.246:8083"   // Replace with your Nexus registry URL
        IMAGE_NAME = "node-app"                  // Replace with your Docker image name
        IMAGE_TAG = "latest"                            
        NEXUS_CREDENTIALS = credentials('nexus') 
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/mahmoud254/jenkins_nodejs_example.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    // docker.build("${IMAGE_NAME}:${IMAGE_TAG}", "-f dockerfile .")
                     sh  """
                        docker build -t 10.105.150.246:8083/repository/${IMAGE_NAME}:${IMAGE_TAG} -f dockerfile .
                       
                        """
                }
            }
        }

        stage('Push to Nexus') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'nexus', passwordVariable: 'NEXUS_PASSWORD', usernameVariable: 'NEXUS_USERNAME')]) {
                        sh """
                            echo ${NEXUS_PASSWORD} | docker login -u ${NEXUS_USERNAME} --password-stdin ${DOCKER_REGISTRY}
                            docker push 10.105.150.246:8083/repository/${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline successfully executed!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}
