apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  username: bXlzcWx1c2Vy   # base64 encoded value of 'mysqluser'
  root-password: cGFzc3dvcmQ=   # base64 encoded value of 'password'
  user-password: cGFzc3dvcmQ=
  database-name: bXlzcWxkYg==  # base64 encoded value of 'mysqldb'
