apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  username: bXlzcWx1c2Vy   # base64 encoded value of 'mysqluser'
  password: cGFzc3dvcmQ=   # base64 encoded value of 'password'
  database-name: bXlzcWxkYg==  # base64 encoded value of 'mysqldb'
